spring:
  datasource:
    url: ${PORTFOLIO_DB_URL:jdbc:mysql://localhost:3306/pfman}
    username: ${PORTFOLIO_DB_USERNAME:root}
    password: ${PORTFOLIO_DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always

eodhd:
  api-key: ${EODHD_API_KEY:}
  base-url: https://eodhd.com/api

server:
  port: 8080

springdoc:
  swagger-ui:
    tryItOutEnabled: true
